# fly.toml app configuration file generated for blue-lake-9016 on 2023-06-30T09:57:14+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blue-lake-9016"
primary_region = "otp"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080 # changed from 3000?
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
