POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "123"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Yasen",
  "number": "888-888-888"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Yasen"
}